SELECT 
DISTINCT O_ORDERDATE AS ORDERDATE,
SUM(O_TOTALPRICE) AS CUMULATIVE_ORDER_PRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
GROUP BY ORDERDATE 
ORDER BY CUMULATIVE_ORDER_PRICE DESC
LIMIT 10