
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('my_first_dbt_model')
              field: id

  - name: accumprice

  - name: custpurchases

  - name: incremental_time

sources:
  - name: sample
    database: snowflake_sample_data
    schema: tpch_sf1
    tables: 
      - name: customer
        columns: 
          - name: c_custkey
            tests: 
              - unique
              - not_null
      - name: orders

##run test on sources data to help with debugging 



